Algoritmo "semnome"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
raio:inteiro
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o raio do circulo: ")
 leia(raio)
 resultado<-(raio*raio)*(3.14)
 escreval("Resultado: ",resultado)
Fimalgoritmo