Algoritmo "atividade52"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson 
// Descrição   : algoritmo que imprime os 10 primeiros números inteiros maiores que 100.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 100 ate 110 passo 1 faca
Escreval(contador)
fimpara
Fimalgoritmo