Algoritmo "atividade55"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson 
// Descrição   : tabuada do 8
// Autor(a)    : Letícia
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis 
contador,resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 10 faca
resultado <- 8 * contador
Escreval("8 x ", contador, " = ", resultado)
fimpara

Fimalgoritmo
