Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero")
leia(numero)
se(numero>=0)entao
escreval("Este numero é positivo")
senao
escreval("Este número é negativo")
fimse

Fimalgoritmo