Algoritmo "pag47b"
// Disciplina
// Professor 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis
 soma,numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
repita
escreval (numero, "+")
numero <- numero+2
soma <- soma+numero
ate numero>500
escreva ("A soma dos pares de 2 á 500 é:", soma)
Fimalgoritmo


Fimalgoritmo